source "https://rubygems.org"

# Jekyll 版本
gem "jekyll", "~> 4.3.0"

# GitHub Pages 兼容
gem "github-pages", group: :jekyll_plugins

# 插件
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
  gem "jekyll-paginate"
  gem "jekyll-gist"
  gem "jekyll-github-metadata"
end

# Windows 和 JRuby 不包含 zoneinfo 文件，所以捆绑 tzinfo-data gem
# 并关联到 x64-mingw32 和 java 平台
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# 性能增强器，适用于监视目录中的更改
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# HTTP 解析器
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

# 主题
gem "minima", "~> 2.5"

# 其他有用的 gems
gem "kramdown-parser-gfm"
gem "rouge"
gem "webrick", "~> 1.7"